name: Deploy Code Coverage Report

on:
    workflow_dispatch:
        inputs:
            coverage-run-id:
                type: string
                description: Workflow run ID with Code Coverage Report artifact
                required: true

permissions:
    id-token: write
    pages: write

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        
        steps:
            - uses: actions/checkout@v4

            - name: Download Code Coverage Report
              uses: actions/download-artifact@v4
              with:
                  github-token: ${{ secrets.GH_PAT }}
                  repository: savify/savify
                  run-id: ${{ github.event.inputs.coverage-run-id }}
                  name: coverage-report
                  path: coverage-report

            - name: Set Favicon
              run: |
                  mv favicon.ico ./coverage-report
                  cd coverage-report
                  sed '7s#.*#<link rel="icon" type="image/x-icon" href="favicon.ico">#' index.html > temp.html
                  mv temp.html index.html
                  cd ..

            - name: Setup Pages
              uses: actions/configure-pages@v2
              
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: coverage-report
        
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v1
